language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly


branch:
  only:
    - master

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Transformers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

notifications:
  email: false

git:
  depth: 99999999


jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
